dist: xenial
language: python
sudo: required
python:
    - 3.7

before_install:
    - docker build -t sloto .
    - pip install codecov
install:
  - pip install -r dev-requirements.txt

script:
    - mypy .
    - make coverage
    - codecov

