version: 2.0

jobs:
    build:
        docker:
          - image: circleci/python:3.7.2
        steps:
          - checkout
          - run: pip install -r dev-requirements.txt
          - run: make test
